/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include <ifxCpu_Irq.h>
#include "IfxScuWdt.h"
#include "SmartCar_Uart.h"
#include "SmartCar_Upload.h"
#include "SmartCar_Oled.h"
#include "SmartCar_MPU.h"
#include "SmartCar_MT9V034.h"
#include "SmartCar_Systick.h"
#include "common.h"
#include "develop_menu.h"
#include "SmartCar_PIT.h"
#include "SmartCar_Eru.h"
#include "Init.h"
#include "long_adc.h"

#pragma section all "cpu0_dsram"
//IfxCpu_syncEvent g_cpuSyncEvent;


int core0_main(void)
{
    IfxCpu_disableInterrupts();
    
    get_clk();
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    //初始化外设
    //屏幕初始化
    SmartCar_Oled_Init();
    //GPIO初始化，20.9保存flash提示灯

//    GPIO_Init(P02,8, PUSHPULL,0);
//    //PWM初始化
    PWM_init();
////    //定时中断初始化
    PIT_init();
////    //编码器初始化
    Encoder_init();
//    //外部中断初始化
//    Eru_init();
//    //串口初始化
//    Uart_init();
//    //创建菜单并完成参量菜单项的赋值
    elec_init();

    CreatMenu();
    //给状态菜单项赋值
    MenuInit();
    PrintMenu();

    IfxCpu_enableInterrupts();


    while(TRUE)
    {
        key get_key=GetKey();
        KeyOperation(get_key);
        if(get_key!=undo)
        PrintMenu();
        if(!GPIO_Read(P20,12))
        PrintMenu();
        if(If_Start == 0)
        {
               if(!GPIO_Read(P20,0))
              {
                 Delay_ms(STM1,3000);
                 If_Start = 1;
              }
        }
        if(If_Start == 1)
        {
               if(!GPIO_Read(P20,8))
              {
                 Delay_ms(STM1,200);
                 If_Start = 0;
              }
        }
//        num_of_encoder = SmartCar_Encoder_Get(GPT12_T2);
        Elec_process();

    }
}

//PIT中断函数  示例
IFX_INTERRUPT(cc60_pit_ch0_isr, 0, CCU6_0_CH0_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    PIT_CLEAR_FLAG(CCU6_0, PIT_CH0);
}


IFX_INTERRUPT(cc60_pit_ch1_isr, 0, CCU6_0_CH1_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    PIT_CLEAR_FLAG(CCU6_0, PIT_CH1);
}

IFX_INTERRUPT(cc61_pit_ch0_isr, 0, CCU6_1_CH0_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    Moto_Speed();
    PIT_CLEAR_FLAG(CCU6_1, PIT_CH0);

}

IFX_INTERRUPT(cc61_pit_ch1_isr, 0, CCU6_1_CH1_ISR_PRIORITY)
{
    enableInterrupts();//开启中断嵌套
    Servo_Elec();
    PIT_CLEAR_FLAG(CCU6_1, PIT_CH1);
}
#pragma section all restore
